#!/usr/bin/env bash

# install ufw if not
sudo apt update
sudo apt install ufw

# allow the given ports
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
sudo ufw enable
sudo ufw reload